import os
os.system("clear")
print ("ALZOMBIE PASSED BU HERE !!")
print ("I NEED FUCK . . . . . .")
prnit ("SULAIMAN ABO ALJOD")
prnit ("ABO KHAOLA")
prnit ("HAKEM AL ARAB")
prnit ("TOPAC AL GHAMED")
prnit ("ALL (ARAB)")
prnit ("WAHSH AL HOMSIE")
prnit ("GHOST AL HALABI")
