import os
os.system("clear")
print ("ALZOMBIE PASSED BU HERE !!")
print ("I NEED FUCK . . . . . .")
print ("SULAIMAN ABO ALJOD")
print ("ABO KHAOLA")
print ("HAKEM AL ARAB")
print ("TOPAC AL GHAMED")
print ("ALL (ARAB)")
print ("WAHSH AL HOMSIE")
print ("GHOST AL HALABI")
